### ISSUE TITLE
Enable client side PDF generation

### ISSUE THREAD

**Issue by me21** [schibsted/jsx-pdf#13]
Right now pdfmake is imported as `require('pdfmake');`. This is correct for server-side PDF rendering.

According to its docs, for client-side rendering, it needs to be imported as
```
var pdfMake = require('pdfmake/build/pdfmake.js');
var pdfFonts = require('pdfmake/build/vfs_fonts.js');
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

Please make it possible to use your package on client side. Right now it throws the following exception: `Uncaught TypeError: fs.readFileSync is not a function` if I try to use it in browser.

**Comment by mtlewis** [comment]
Hey @me21 - let us know if v2.0.0 matches your use case any better.  This was a great suggestion that I think has made the library a lot cleaner, so thanks very much for the feedback!

The only thing that still may cause issues for you when running this code in a browser is the fact that we attempt to require some lodash modules in the transpiled script.  In the future we might provide a rollup bundle containing these extra modules so that there's no extra build step required to handle this.
